### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ViHammer** [nanoporetech/bonito#247]
I am currently trying to run Bonito on our GPU Server. We have two Tesla v100 with 16GB each. When running bonito on GPU 0 with the following command, basecalling is successfull:
~~~
bonito basecaller dna_r9.4.1_e8_hac@v3.3 fast5_pass/ \
--modified-bases 5mC \
--device cuda:0 \
--reference GRCh38.fa \
> basecalls_with_mods.bam
~~~

But if I want to start it on GPU 1 (ONLY changing the `--device` flag to `cuda:1`), I get the following error on an otherwise empty server (`nvidia-smi` only lists my bonito process):
~~~
RuntimeError: CUDA out of memory. Tried to allocate 750.00 MiB (GPU 1; 15.78 GiB total capacity; 178.27 MiB already allocated; 262.50 MiB free; 434.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
~~~
According to this error message, most of the memory is neither allocated, nor reserved, but only 262Mb are free. Am I understanding this error message correctly? Is this an issue with our Cuda installation, or with bonito?

If I have already started a bonito process on GPU 0, and want to start a second one on GPU 1, I get the error message described in issue #233 

Thanks in advance,
Vincent.

**Comment by iiSeymour** [comment]
Hi @ViHammer when using multi-gpu systems I'd recommend using the `CUDA_VISIBLE_DEVICES` environment variable to select the GPU to use. 

```
$ export CUDA_VISIBLE_DEVICES=0
$ bonito basecaller dna_r9.4.1_e8_hac@v3.3 reads_1/ --modified-bases 5mC --reference GRCh38.fa > calls_1.bam
$
$ export CUDA_VISIBLE_DEVICES=1
$ bonito basecaller dna_r9.4.1_e8_hac@v3.3 reads_2/ --modified-bases 5mC --reference GRCh38.fa > calls_2.bam
```

**Comment by ViHammer** [comment]
That fixed it! Thank you very much.
