### ISSUE TITLE
Error while trying to use bonito train : 'RuntimeError: CUDA out of memory...'

### ISSUE THREAD

**Issue by DjampaKozlowski** [nanoporetech/bonito#275]
Hello,

I'm currently trying to run bonito train (v-0.5.3) to fine tune an existing model (after a step of basecalling to produce ctc).

I'm encountering the following error : 

`
RuntimeError: CUDA out of memory. Tried to allocate 3.91 GiB (GPU 0; 31.75 GiB total capacity; 27.46 GiB already allocated; 2.93 GiB free; 27.59 GiB reserved in total by PyTorch) If
 reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

when trying to execute the following script on a Centos 7 HPC cluster using slurm as workload manager (using a Tesla-V100):

```
#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mail-type=BEGIN,END,FAIL


### Bonito : fine tune original model with new data
#

##  Load modules
module purge
module load miniconda
module load cuda/11.0 # also tried module load cuda/10.2

##  Activate conda env
conda activate bonito_env

##  Re-train original model with new data 
bonito train --epochs 1 --lr 5e-4 --batch 256 --device cuda:0 --pretrained dna_r9.4.1_e8.1_sup@v3.3 --directory $1 $2
```
where $1 correspond to the the ctc-basecalling output directory and $2 to the current output path
 

Here are the suggested solutions from other post I already tried without succes : 
- change the batch size value : 128 and 64.
- change the '--device' parameter : no '--device' parameter or '--device cuda'.
- export the following variables OMP_NUM_THREADS=1 and/or CUDA_LAUNCH_BLOCKING=1

 Every time, I ended up with the **exact same error message** including the amount of free/allocated memory. 

But things get weirder. When executing the following python script (from a batch script, e.g. through a sbatch command as for bonito call) : 

```
import torch

# code from https://stackoverflow.com/questions/48152674/how-to-check-if-pytorch-is-using-the-gpu

# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    cur_device = torch.cuda.current_device()
    print(torch.cuda.get_device_name(cur_device))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(cur_device)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(cur_device)/1024**3,1), 'GB')
```

I obtain the following output : 

Using device: cuda

Tesla V100-SXM2-32GB
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB

Hence, there is plenty of available memory which is consistent with the ressources allocation.  

NB: 
- Ressources allocation (nb_CPU, assignated GPU, ...), loaded modules (cuda 10.2 or 11, same error message and miniconda3), and used conda environment  are strictly identical between the python script and the bonito train calls (all the tests).
- The conda environment run python 3.9.12. I also tried using and environment running python 3.8,  but once again I ended up with the same error.

I hope I have been clear and precise enough. Any tip would be greatly appreciated. 

Djampa

**Comment by iiSeymour** [comment]
Is this running on node with more than one GPU? If so, do you see the same thing if you `export CUDA_VISIBLE_DEVICES=0` or `CUDA_VISIBLE_DEVICES=0 bonito train --epochs 1 --lr 5e-4`?

**Comment by DjampaKozlowski** [comment]
Hello @iiSeymour ,

Thank you for your quick answer !

> Is this running on node with more than one GPU

Yes the node I'm running is equipped with 4 Nvidia Tesla V100 32 GB GPU cards but I only required 1 in the ressources requirements.

> If so, do you see the same thing if you export CUDA_VISIBLE_DEVICES=0 or CUDA_VISIBLE_DEVICES=0 bonito train --epochs 1 --lr 5e-4

I tried your suggestions but unfortunately it didn't work. 

I tried the following code :

```
...

export CUDA_VISIBLE_DEVICES=0
bonito train --epochs 1 --lr 5e-4 --pretrained dna_r9.4.1_e8.1_sup@v3.3 --directory $1 $2
```
and ended up with the following error message : 

```
[0/25420]:   0%|                                                                           | [00:00]Error - an illegal memory access was encountered 
[0/25420]:   0%|                                                                           | [00:06]
Traceback (most recent call last):
  File "/home/dkozlowski/.conda/envs/bonito_env/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')())
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/cli/train.py", line 99, in main
    trainer.fit(workdir, args.epochs, lr)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 210, in fit
    train_loss, duration = self.train_one_epoch(loss_log, lr_scheduler)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 135, in train_one_epoch
    losses, grad_norm = self.train_one_step(batch)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 99, in train_one_step
    losses_ = self.criterion(scores_, targets_, lengths_)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/crf/model.py", line 177, in loss
    return self.seqdist.ctc_loss(scores.to(torch.float32), targets, target_lengths, **kwargs)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/crf/model.py", line 122, in ctc_loss
    logz = logZ_cu(stay_scores, move_scores, target_lengths + 1 - self.state_len)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_koi-0.0.9-py3.9-linux-x86_64.egg/koi/ctc.py", line 115, in logZ_cu
    return LogZ.apply(stay_scores, move_scores, target_lengths, _simple_lattice_fwd_bwd_cu, S)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_koi-0.0.9-py3.9-linux-x86_64.egg/koi/ctc.py", line 53, in forward
    g = S.dsum(torch.cat([S.mul(alpha[:-1], beta_stay), S.mul(alpha[:-1], beta_move)], dim=2), dim=2)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
As advised in this error message, I also exported CUDA_LAUNCH_BLOCKING=1 alongside with CUDA_VISIBLE_DEVICES=0 : 

```
...
export CUDA_VISIBLE_DEVICES=0
export CUDA_LAUNCH_BLOCKING=1

bonito train --epochs 1 --lr 5e-4 --pretrained dna_r9.4.1_e8.1_sup@v3.3 --directory $1 $2
```

and a new error message arose: 

```
[loading data]
[validation set not found: splitting training set]
[loading model]
[using pretrained model dna_r9.4.1_e8.1_sup@v3.3]
[0/25420]:   0%|                                                                           | [00:00]Error - an illegal memory access was encountered 
[0/25420]:   0%|                                                                           | [00:04]
Traceback (most recent call last):
  File "/home/dkozlowski/.conda/envs/bonito_env/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')())
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/cli/train.py", line 99, in main
    trainer.fit(workdir, args.epochs, lr)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 210, in fit
    train_loss, duration = self.train_one_epoch(loss_log, lr_scheduler)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 135, in train_one_epoch
    losses, grad_norm = self.train_one_step(batch)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 99, in train_one_step
    losses_ = self.criterion(scores_, targets_, lengths_)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/crf/model.py", line 177, in loss
    return self.seqdist.ctc_loss(scores.to(torch.float32), targets, target_lengths, **kwargs)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/crf/model.py", line 122, in ctc_loss
    logz = logZ_cu(stay_scores, move_scores, target_lengths + 1 - self.state_len)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_koi-0.0.9-py3.9-linux-x86_64.egg/koi/ctc.py", line 115, in logZ_cu
    return LogZ.apply(stay_scores, move_scores, target_lengths, _simple_lattice_fwd_bwd_cu, S)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_koi-0.0.9-py3.9-linux-x86_64.egg/koi/ctc.py", line 53, in forward
    g = S.dsum(torch.cat([S.mul(alpha[:-1], beta_stay), S.mul(alpha[:-1], beta_move)], dim=2), dim=2)
RuntimeError: CUDA error: an illegal memory access was encountered
``` 
Even if the end of the error message is different, it seems the exact same part of the program are impacted. 


Nb, I also tried  what follow but none of it helped:
- to use bonito train with the '--device cuda:0' argument alonside with the env var CUDA_VISIBLE_DEVICES=0.
- to add the OMP_NUM_THREADS=1 env var. 

Thank you again

**Comment by vellamike** [comment]
@DjampaKozlowski it seems like when you run with `CUDA_VISIBLE_DEVICES=0` you get past the first error, bonito training progress further, and you hit a new error (illegal memory access). I am guessing that with the first error you didn't see the progress bars, is that right?

Would it be possible to share some of your training data with me to reproduce this issue? It's also been reported in #233 and so far we haven't got to the bottom of it.

**Comment by DjampaKozlowski** [comment]
Hello @vellamike , 

Thank you for answering. 

>  I am guessing that with the first error you didn't see the progress bars, is that right?

Actually when running bonito train without the CUDA_VISIBLE_DEVICES=0 var, I do have the progress bar displayed :

```
[loading data]
[validation set not found: splitting training set]
[loading model]
[using pretrained model dna_r9.4.1_e8.1_sup@v3.3]
[0/25420]:   0%|                                                                           | [00:02]
Traceback (most recent call last):
  File "/home/dkozlowski/.conda/envs/bonito_env/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')())
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/cli/train.py", line 99, in mai
n
    trainer.fit(workdir, args.epochs, lr)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 210, in fit
    train_loss, duration = self.train_one_epoch(loss_log, lr_scheduler)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 135, in tra
in_one_epoch
    losses, grad_norm = self.train_one_step(batch)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 98, in trai
n_one_step
    scores_ = self.model(data_)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/crf/model.py", line 166, in fo
rward
    return self.encoder(x)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/nn.py", line 41, in forward
    return super().forward(x)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/nn.py", line 111, in forward
    scores = self.linear(x)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkozlowski/.conda/envs/bonito_env/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA out of memory. Tried to allocate 3.91 GiB (GPU 0; 31.75 GiB total capacity; 27.46 GiB already allocated; 2.93 GiB free; 2
7.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See 
documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Sorry, I should have pasted the whole error message in my initital post.

> Would it be possible to share some of your training data with me to reproduce this issue?

Of course, I'd be glad to. Shall I create an archive and send you a download link? Or do you prefer another way ?

**Comment by vellamike** [comment]
Download link would be great! If you could include instructions to
reproduce it would be perfect.

**Comment by cdebuck** [comment]
I am experiencing similar problems when trying to test the bonito train option.
For me the type of error depends on the batch size I'm setting.

If I set the default batch size, I get the 'CUDA out of memory error':
```
bonito train --pretrained dna_r9.4.1_e8_sup@v3.3--device cuda:0 --epochs 1 --lr 5e-4 --directory ctc-train_test_dir/ test_fine_tuned_model/
```

```
[loading data]
[validation set not found: splitting training set]
[loading model]
[using pretrained model dna_r9.4.1_e8_sup@v3.3]
[0/3526]:   0%|                                                                            | [0/3526]:   0%|                                                                            | [00:00]
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/cli/train.py", line 99, in main
    trainer.fit(workdir, args.epochs, lr)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/training.py", line 210, in fit
    train_loss, duration = self.train_one_epoch(loss_log, lr_scheduler)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/training.py", line 135, in train_one_epoch
    losses, grad_norm = self.train_one_step(batch)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/training.py", line 99, in train_one_step
    losses_ = self.criterion(scores_, targets_, lengths_)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/crf/model.py", line 177, in loss
    return self.seqdist.ctc_loss(scores.to(torch.float32), targets, target_lengths, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/crf/model.py", line 120, in ctc_loss
    scores = self.normalise(scores)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/crf/model.py", line 49, in normalise
    return (scores - self.logZ(scores)[:, None] / len(scores))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/crf/model.py", line 46, in logZ
    return logZ_cu_sparse(Ms, self.idx, alpha_0, beta_T, S)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/koi/ctc.py", line 261, in logZ_cu_sparse
    return _LogZ.apply(Ms, idx, v0, vT, S, K)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/koi/ctc.py", line 243, in forward
    logZ, Ms_grad = logZ_fwd_cu(Ms, idx, v0, vT, S, K)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/koi/ctc.py", line 205, in logZ_fwd_cu
    Ms_grad = Ms.new_full((T, N, C, NZ), S.zero)
RuntimeError: CUDA out of memory. Tried to allocate 2.44 GiB (GPU 0; 15.78 GiB total capacity; 11.62 GiB already allocated; 750.75 MiB free; 13.65 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

If I use smaller batch sizes (I've set --batch with different values ranging from 3-32), I get the illegal memory error:

```
[loading data]
[validation set not found: splitting training set]
[loading model]
[using pretrained model dna_r9.4.1_e8_sup@v3.3]
[0/3526]:   0%|                                                                            | [00:00]Error - an illegal memory access was encountered
[0/3526]:   0%|                                                                            | [00:00]
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bonito", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/cli/train.py", line 99, in main
    trainer.fit(workdir, args.epochs, lr)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/training.py", line 210, in fit
    train_loss, duration = self.train_one_epoch(loss_log, lr_scheduler)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/training.py", line 135, in train_one_epoch
    losses, grad_norm = self.train_one_step(batch)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/training.py", line 99, in train_one_step
    losses_ = self.criterion(scores_, targets_, lengths_)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/crf/model.py", line 177, in loss
    return self.seqdist.ctc_loss(scores.to(torch.float32), targets, target_lengths, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bonito/crf/model.py", line 122, in ctc_loss
    logz = logZ_cu(stay_scores, move_scores, target_lengths + 1 - self.state_len)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/koi/ctc.py", line 115, in logZ_cu
    return LogZ.apply(stay_scores, move_scores, target_lengths, _simple_lattice_fwd_bwd_cu, S)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/koi/ctc.py", line 53, in forward
    g = S.dsum(torch.cat([S.mul(alpha[:-1], beta_stay), S.mul(alpha[:-1], beta_move)], dim=2), dim=2)
RuntimeError: CUDA error: an illegal memory access was encountered
```

I am using bonito version 0.5.3 build for CUDA 11.3.
I have also tried the CUDA_VISIBLE_DEVICES=0 and CUDA_LAUNCH_BLOCKING=1 as suggested above, but it makes no difference.

**Comment by vellamike** [comment]
Hi @cdebuck - If you could send me data and instructions to reproduce this it would be very helpful. We haven't seen this issue internally yet.

**Comment by DjampaKozlowski** [comment]
Hello @vellamike,

Sorry, It took ages to upload data on a secured server. Could you please send me your mail address so I can send you the download link and the workflow I used ?

**Comment by vellamike** [comment]
No worries. ***@***.***

**Comment by vellamike** [comment]
@DjampaKozlowski @cdebuck I was able to reproduce this problem internally now and I'm investigating the cause.

**Comment by vellamike** [comment]
@DjampaKozlowski @cdebuck  this problem is now fixed in the latest version of Koi (0.1.1). The next release of Bonito will include the fix, but in the meantime you can get a working version yourself by installing Bonito from source and using the latest version of Koi:

```
git clone https://github.com/nanoporetech/bonito.git
cd bonito
#change L11 in requirements.txt to be ont-koi==0.1.1 (not 0.1.0)
pip install --upgrade pip
pip install -r requirements.txt
python setup.py install
```

**Comment by DjampaKozlowski** [comment]
Hello @vellamike ,

Thank you so much ! It resolved my issue ! 

NB : @iiSeymour already added the modification in the requirements. Hence, downloading bonito using `git clone https://github.com/nanoporetech/bonito.git` would work. But for those who'd rather prefer to download it as an archive, the 0.5.3 release has not been fixed yet (koi version 0.09 in  requirements.txt). Hence, you should  modify the requirements.txt as mentioned above.

**Comment by cdebuck** [comment]
Thank you providing a fix for this issue. I do have a question about the implementation, because I cannot manage to install bonito from the cloned git repo for CUDA version 11.3.

Previously I installed bonito via:
`pip install -f https://download.pytorch.org/whl/torch_stable.html ont-bonito-cuda113`

But this time, I would like to use the updated version of bonito with several fixes (including the problem described in this issue, but also other fixes). I assumed that I would be able to do the following:

```
git clone https://github.com/nanoporetech/bonito.git
cd bonito
```
Then I changed line 11 in requirements-cuda113.txt to ont-koi==0.1.1
```
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install -r requirements-cuda113.txt
```

However, this gives the following error (the other packages were installed without problems):
```
ERROR: Could not find a version that satisfies the requirement torch==1.11+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0)
ERROR: No matching distribution found for torch==1.11+cu113
```

Thus, the line `torch==1.11+cu113` in requirements-cuda113.txt did not work.
Was my approach correct? Should I have used the regular requirements.txt file instead? Do you have a suggestion for how I could install the most recent version of bonito for CUDA 11.3?

**Comment by vellamike** [comment]
@cdebuck Can you just do the following:

```
git clone https://github.com/nanoporetech/bonito.git
cd bonito
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
python setup.py install
```

**Comment by iiSeymour** [comment]
@cdebuck you need specify the pytorch index for the CUDA 11.3 build of PyTorch when installing the requirements. 

```
$ python3 -m venv venv3
$ source venv3/bin/activate
$ pip install --upgrade pip
$ pip install -f https://download.pytorch.org/whl/torch_stable.html -r requirements-cuda113.txt
$ CUDA_VERSION=113 python setup.py install
```

**Comment by cdebuck** [comment]
@vellamike @iiSeymour thank you for the help! I tried both options in separate environments and they both worked well.

**Comment by iiSeymour** [comment]
Good to hear 👍🏻 

_Note: you only need CUDA 11.3 builds if you are running on Ampere GPUs (A100, ect)._

**Comment by chilampoon** [comment]
> 

I still got this error after updating koi to 0.1.1

```
CUDA_VISIBLE_DEVICES=2 bonito train ./dna_r9 --directory dna_r9.4.1 --epochs 1 --lr 5e-4 -f
[loading data]
[loading model]
[0/1221470]:   0%|                                                                         | [00:00]Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
[0/1221470]:   0%|                                                                         | [00:00]
Traceback (most recent call last):
  File "/home/pclam/miniconda3/envs/bonito/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito==0.5.3', 'console_scripts', 'bonito')())
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/cli/train.py", line 99, in main
    trainer.fit(workdir, args.epochs, lr)
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 210, in fit
    train_loss, duration = self.train_one_epoch(loss_log, lr_scheduler)
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 135, in train_one_epoch
    losses, grad_norm = self.train_one_step(batch)
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/ont_bonito-0.5.3-py3.9.egg/bonito/training.py", line 104, in train_one_step
    self.scaler.scale(total_loss).backward()
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/pclam/miniconda3/envs/bonito/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 900.00 MiB (GPU 0; 10.92 GiB total capacity; 9.41 GiB already allocated; 729.38 MiB free; 9.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

the GPU is also like
```
GeForce GTX 1080 Ti
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
```

**Comment by cdebuck** [comment]
@chilampoon I also needed to decrease the batch size (with --batch) to avoid out of memory errors. Maybe that might help you too?

**Comment by chilampoon** [comment]
@cdebuck thanks! Yep I've tried changing the batch size to 32 (default is 64) and got these...:

```
[loading data]
[loading model]
[0/1221470]:   0%|                                                                         | [00:00]Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
[32/1221470]:   0%|                        | [00:01, loss=288063437890022677088829431410065408.0000]Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
[64/1221470]:   0%|                        | [00:02, loss=288112147562406833904628949556658176.0000]Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
[96/1221470]:   0%|                        | [00:02, loss=288144468649709754349988922641088512.0000]Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
Error - no kernel image is available for execution on the device 
[128/1221470]:   0%|                       | [00:03, loss=288337350798208415411205664143310848.0000]Error - no kernel image is available for execution on the device 
```
The CTC loss was big and increasing... that's weird

**Comment by tycheyoung** [comment]
@chilampoon Hi, I'm facing the same problem. Have you resolved it?
