### ISSUE TITLE
CPU-only environment

### ISSUE THREAD

**Issue by dkurt** [nanoporetech/bonito#70]
When do import without CUDA:
```
import seqdist.sparse
from seqdist.ctc_simple import logZ_cupy
```
the following error appears.
```
original error: libcublas.so.10: cannot open shared object file: No such file or directory
```

To resolve it, we need a CPU/NumPY version of `seqdist.sparse.logZ`

**Comment by apredeus** [comment]
I'm trying to use @dkurt 's version on a CPU-only cluster and getting the same error. It can't be done yet, can it?

**Comment by dkurt** [comment]
@apredeus, for now https://github.com/nanoporetech/bonito/pull/52 only works with v2 model (the latest is v3):

```bash
bonito basecaller dna_r9.4.1@v2 --use_openvino --device=cpu /data/reads > basecalls.fasta
```

I'll try to port logZ to NumPy in case of CPU device and update a pull request.

**Comment by apredeus** [comment]
Thank you! I'm getting the following error with v2 

> NameError: name 'IECore' is not defined

**Comment by dkurt** [comment]
@apredeus, please type `export LD_LIBRARY_PATH=$(pwd)/venv3/lib:$LD_LIBRARY_PATH`

**Comment by apredeus** [comment]
I did, but it didn't help.

**Comment by dkurt** [comment]
@apredeus, I guess that this is OS/Python version limitation. Can you please share your configuration?

**Comment by apredeus** [comment]
I've made a conda env with python 3.7 and virtual env within it. It's a 64-core server running Debian 8. Here's the output of `pip list`: 

> Package            Version    Location
> ------------------ ---------- -------------------
> alembic            1.4.3
> attrs              20.3.0
> cached-property    1.5.2
> certifi            2020.11.8
> chardet            3.0.4
> cliff              3.5.0
> cmd2               1.4.0
> colorama           0.4.4
> colorlog           4.6.2
> crf-beam           0.0.1a0
> cupy-cuda102       8.1.0
> Cython             0.29.21
> fast-ctc-decode    0.2.5
> fastrlock          0.5
> future             0.18.2
> h5py               3.1.0
> idna               2.8
> importlib-metadata 2.0.0
> joblib             0.17.0
> Mako               1.1.3
> mappy              2.17
> MarkupSafe         1.1.1
> numpy              1.16.3
> ont-bonito         0.3.1      /pub37/alexp/bonito
> ont-fast5-api      3.1.6
> openvino-python    2021.1
> optuna             1.1.0
> packaging          20.4
> parasail           1.2
> pbr                5.5.1
> pip                20.2.4
> prettytable        0.7.2
> progressbar33      2.4
> pyparsing          2.4.7
> pyperclip          1.8.1
> python-dateutil    2.8.1
> python-editor      1.0.4
> PyYAML             5.3.1
> requests           2.22.0
> scipy              1.5.4
> seqdist            0.0.1
> setuptools         47.1.0
> six                1.15.0
> SQLAlchemy         1.3.20
> stevedore          3.2.2
> tbb                2020.3.254
> toml               0.10.0
> torch              1.5.0
> tqdm               4.31.1
> urllib3            1.25.11
> wcwidth            0.2.5
> wheel              0.35.1
> zipp               3.4.0

`echo $LD_LIBRARY_PATH `

> /pub37/alexp/bonito/venv3/lib:/pub37/alexp/miniconda3/lib:

**Comment by dkurt** [comment]
@apredeus, Are you able to use Docker? If so, I can recommend this approach due there is no binaries of  OpenVINO for Debian 8.

1. Create a file with name "Dockerfile" and the following content:

```dockerfile
FROM ubuntu:18.04

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      python3-minimal \
      python3-pip \
      git \
      build-essential \
      python3-dev \
      libz-dev

RUN git clone -b openvino --depth 1 https://github.com/dkurt/bonito /bonito

RUN cd /bonito && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install setuptools && \
    python3 -m pip install -r requirements.txt && \
    python3 setup.py develop && \
    bonito download --models

RUN useradd -ms /bin/bash -G users bonito && \
    chown bonito -R /home/bonito

USER bonito

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```
2. Build image
```bash
docker build . -t bonito
```
3. Run
```bash
export INPUT_DIR=$(pwd)/reads
export OUTPUT_DIR=$(pwd)/output

mkdir -p ${OUTPUT_DIR}

docker run \
  -v "${INPUT_DIR}":"/reads" \
  -v "${OUTPUT_DIR}":"/output" \
  bonito:latest \
  /bin/sh -c "bonito basecaller dna_r9.4.1@v2 /reads --use_openvino --device=cpu > /output/basecalls.fasta"
```

**Comment by apredeus** [comment]
@dkurt thank you, but I can't use Docker on our cluster. Thank you for your help though, I really appreciate it. Perhaps I'll look for some GPU options in a little while.

**Comment by dkurt** [comment]
@apredeus, I'll let you know if there is a chance to make it work without Docker.

**Comment by dkurt** [comment]
> I'll try to port logZ to NumPy in case of CPU device and update a pull request.

I've ported LogZ to NumPy so now v3 model also work on CPU with OpenVINO. See updated https://github.com/nanoporetech/bonito/pull/52.

> @apredeus, I'll let you know if there is a chance to make it work without Docker.

I can recommend to build OpenVINO with Python binding from source instead of using pip distro:

```bash
git clone --depth 1 https://github.com/openvinotoolkit/openvino/
cd openvino
git submodule update --init --recursive
mkdir build & cd build

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_CLDNN=OFF \
  -DENABLE_VPU=OFF \
  -DENABLE_TESTS=OFF \
  -DENABLE_PYTHON=ON \
  -DENABLE_OPENCV=OFF \
  -DENABLE_SAMPLES=OFF \
  -DPYTHON_EXECUTABLE=`which python3` \
  -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
  -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..

make -j$(nproc)
```
(not sure which Python version you have so replace 3.6 to appropriate)

then
```bash
export LD_LIBRARY_PATH=/path/to/openvino/bin/intel64/Release/lib/:$LD_LIBRARY_PATH
export PYTHONPATH=/path/to/openvino/bin/intel64/Release/lib/python_api/python3.6/:$PYTHONPATH
```

**Comment by colindaven** [comment]
Thanks @dkurt ! That was really helpful.

I followed the docker recipe and bonito is now running.

Changes for others:

You might need to add your proxy to ENV if behind a firewall.
```

# Add my proxy
ENV http_proxy 'http://YOURPROXYIP:8080'
ENV https_proxy 'http://YOURPROXYIP:8080'

# Create user bonito, same id gid as YOUR_EXTERNAL_NFS_USER (here 9415). To solve "permission denied" problem
RUN groupadd -g 9415 bonito
RUN useradd -m -u 9415 -g 9415 -s /bin/bash bonito
RUN chown bonito -R /home/bonito


```

**Comment by dkurt** [comment]
@colindaven, I suggest to use `--build-arg` during build (so Dockerfile can be clear):
```
docker build . --build-arg http_proxy=http://YOURPROXYIP:8080 --build-arg https_proxy=http://YOURPROXYIP:8080
```

**Comment by colindaven** [comment]
@dkurt here's an interesting error for you, perhaps after basecalling completed (results are present) ?

```
 docker run \
>   -v "${INPUT_DIR}":"/reads" \
>   -v "${OUTPUT_DIR}":"/output" \
>   bonito:latest \
>   /bin/sh -c "bonito basecaller dna_r9.4.1@v2 /reads --use_openvino --device=cpu > /output/basecalls.fasta"
> loading model
> calling: 5366 reads [1:04:48,  1.36 reads/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/bonito/bonito/multiprocessing.py", line 103, in run
    for (k, v) in self.iterator:
  File "/bonito/bonito/ctc/basecall.py", line 26, in <genexpr>
    (read, {'scores': stitch(v, overlap, model.stride)}) for read, v in scores
  File "/bonito/bonito/util.py", line 210, in <genexpr>
    for k, group in groupby(batches, itemgetter(0))
  File "/bonito/bonito/util.py", line 209, in <listcomp>
    (k, concat([v for (k, v) in group], dim))
  File "/bonito/bonito/util.py", line 204, in <genexpr>
    (k, select_range(v, start, end, dim))
  File "/bonito/bonito/ctc/basecall.py", line 23, in <genexpr>
    (k, compute_scores(model, v)) for k, v in batchify(chunks, batchsize)
  File "/bonito/bonito/ctc/basecall.py", line 41, in compute_scores
    probs = permute(model(chunks), 'TNC', 'NTC')
  File "/bonito/bonito/openvino/model.py", line 90, in __call__
    config=config, num_requests=0)
  File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: can't protect

> calling: 5995 reads [1:05:02, 22.92 reads/s]
```

**Comment by dkurt** [comment]
@colindaven, can you please add more details including Dockerfile, run command and hardware?

**Comment by colindaven** [comment]
@dkurt All exactly as you specified in
https://github.com/nanoporetech/bonito/issues/70#issuecomment-731395436

with the exceptions of proxy and uid/gid I detailed in my above comment.

Hardware is trickier, what do you need to know ?
Basically 80 core, 192GB RAM, Ubuntu 20.04 64bit. No GPU.

```
processor       : 79
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
stepping        : 4
microcode       : 0x2006a08
cpu MHz         : 1000.414
cache size      : 28160 KB
physical id     : 1
siblings        : 40
core id         : 28
cpu cores       : 20
apicid          : 121
initial apicid  : 121
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4802.12
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by dkurt** [comment]
@colindaven, For Ubuntu 20 please add the following lines to Docker:
```bash
RUN curl -o GPG-PUB-KEY-INTEL-OPENVINO-2021 https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
    apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
    echo "deb https://apt.repos.intel.com/openvino/2021 all main" | tee - a /etc/apt/sources.list.d/intel-openvino-2021.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends intel-openvino-dev-ubuntu20-2021.1.110
```

because `openvino-python` for now supports only Ubuntu 18.04
Then, instead of `export LD_LIBRARY_PATH=$(pwd)/venv3/lib:$LD_LIBRARY_PATH` please do `source /opt/intel/openvino_2021/bin/setupvars.sh`

Sorry for confusion - we just released first pip package a two months ago.

**Comment by colindaven** [comment]
Apologies, just the system software is 20.04, I am using your 18.04 dockerfile. I've built the docker image in Singularity which is better/easier for cluster usage, and am testing now. Next week I'll try to dig out time to get the v3 bonito models a go :

> I've ported LogZ to NumPy so now v3 model works


`singularity exec bonito_031_sing.sif bonito -v
`
bonito 0.3.1

Also, I see I actually need to explicitly call 
`--use_openvino
`
in the bonito basecaller command (which I'm not doing yet ...).

**Comment by dkurt** [comment]
@colindaven, sorry for delay, can you please share some commands to reproduce the problem? Singularity docs cannot help me :)

**Comment by dkurt** [comment]
> I've made a conda env with python 3.7 and virtual env within it. It's a 64-core server running Debian 8. Here's the output of pip list:

@apredeus, The latest version of pull request now uses `manylinux2014` wheel. It supports Python 3.7 as well. Can you please try?

**Comment by apredeus** [comment]
I will, thank you very much! I'll get back with results soon.

**Comment by apredeus** [comment]
Hello @dkurt, 

I think I got lost in installation instructions... I've reinstalled the version from your fork using deverlopers instructions, and get "no CUDA found" error when trying to run bonito. What's a recommended way of installation for CPU-only version? Thank you!

**Comment by dkurt** [comment]
@apredeus, please verify that `git log` shows the latest commit from the branch.

**Comment by colindaven** [comment]
Hi @dkurt : I managed to get to use the bonito-like weights in the performant guppy program (v4.4.1 I believe, with bonito models from the rerio repository). It required a bit of configuring detailed here https://github.com/colindaven/guppy_on_slurm/blob/master/runbatch_singularity_guppy.sh

This met my needs and ran simply and easily (I need to CPU re-basecall quite a lot of runs). 

Thanks!

**Comment by pmitev** [comment]
Hi @dkurt we tried your docker solution and we are running in this particular problem (both in docker and Singularity).

``` bash
$ ./bonito.sif 
Singularity> bonito basecaller dna_r9.4.1@v2 /reads --use_openvino --device=cpu | tee basecalls.fasta
> loading model
Traceback (most recent call last):
  File "/usr/local/bin/bonito", line 33, in <module>
    sys.exit(load_entry_point('ont-bonito', 'console_scripts', 'bonito')())
  File "/bonito/bonito/__init__.py", line 34, in main
    args.func(args)
  File "/bonito/bonito/cli/basecaller.py", line 28, in main
    model = load_model(args.model_directory, args.device, weights=int(args.weights), use_openvino=args.use_openvino)
  File "/bonito/bonito/util.py", line 299, in load_model
    Model = load_symbol(config, "Model")
  File "/bonito/bonito/util.py", line 265, in load_symbol
    imported = import_module(config['model']['package'])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/bonito/bonito/ctc/__init__.py", line 1, in <module>
    from .model import Model
  File "/bonito/bonito/ctc/model.py", line 6, in <module>
    from bonito.nn import Permute, activations
ImportError: cannot import name 'activations
```
We really appreciate your work.
Best,
Pavlin and Björn

**Comment by dkurt** [comment]
Hi, @pmitev! I just fixed the problem by the latest commit. Please take a look at https://github.com/nanoporetech/bonito/pull/52. Thanks for catching this!

**Comment by pmitev** [comment]
Thanks!
